= some_puff1(1)
Lenik <zephyr@bodz.net>
v{project-version}, {project-year}
:doctype: manpage
:manmanual: User Commands
:mansource: zephyr
:man-linkstyle: blue R <>
:nofooter:

== Name

some_puff1 - concatenate files to standard output

== Synopsis

*some_puff1* [_OPTION_]... [_FILE_]...

== Description

Copy each _FILE_ to standard output in order.
If _FILE_ is a single dash (*-*), read standard input at that position.
If no _FILE_ is given, read standard input once.

*some_puff1* is similar in spirit to *cat*(1): it writes the concatenation of
inputs to standard output.

== Options

*-v, --verbose*::
  Print status messages to standard error.
  Repeat for more verbose logging.

*-q, --quiet*::
  Suppress messages that would be printed by *--verbose*.

*-h, --help*::
  Print a usage summary and exit successfully.

*--version*::
  Print version and license information and exit successfully.

== Exit status

*0*::
  Success.

*1*::
  An error occurred (invalid options, unreadable file, or I/O error).

== Author

Written by {project-author} <{project-email}>.

== Copyright

Copyright (C) {project-year}.
License AGPL-3.0-or-later.
This is free software: you are free to change and redistribute it under the
terms of the GNU Affero General Public License.
There is NO WARRANTY, to the extent permitted by law.
