# SPDX-License-Identifier: AGPL-3.0-or-later
"""Numbered zephyr lint rules (ZL001+)."""

from __future__ import annotations

from .registry import RuleRegistry, StdRule

_LINT_RULES: tuple[StdRule, ...] = (
    StdRule("ZL001", "source.long", "Source file length; extract to package subdirectory", "varies"),
    StdRule("ZL002", "source.size", "No oversized source files", "ok"),
    StdRule("ZL003", "layout.*", "Required layout file present or missing", "varies"),
    StdRule("ZL004", "layout.docs", "AsciiDoc man page sources under docs/", "varies"),
    StdRule("ZL005", "layout.completion", "Bash completion script at project root", "varies"),
    StdRule("ZL006", "layout.VERSION", "VERSION file synced with changelog", "varies"),
    StdRule("ZL007", "layout.pre-commit", "Git pre-commit hook syncs VERSION", "varies"),
    StdRule("ZL008", "debian.build-depends.*", "debian/control Build-Depends entry", "varies"),
    StdRule("ZL009", "debian.debhelper", "debhelper-compat in Build-Depends", "varies"),
    StdRule("ZL010", "debian.Architecture", "debian/control Architecture field", "varies"),
    StdRule("ZL011", "debian.Architecture.elf", "ELF binary vs Architecture: all", "error"),
    StdRule("ZL012", "debian.Homepage", "debian/control Homepage field", "varies"),
    StdRule("ZL013", "debian.rules", "debian/rules uses dh meson debian/build", "varies"),
    StdRule("ZL014", "debian.copyright", "debian/copyright mentions AGPL", "varies"),
    StdRule("ZL015", "debian.source.format", "debian/source/format native 3.0", "ok"),
    StdRule("ZL016", "debian.VERSION_sync", "VERSION matches debian/changelog", "varies"),
    StdRule("ZL017", "debian.Depends.bash-shlib", "bash package Depends includes bash-shlib", "varies"),
    StdRule("ZL018", "meson.project", "meson.build project() call", "varies"),
    StdRule("ZL019", "meson.license", "meson license AGPL-3.0-or-later", "varies"),
    StdRule("ZL020", "meson.project_*", "meson project_author/email/year", "varies"),
    StdRule("ZL021", "meson.version_source", "Meson version from zfr version", "varies"),
    StdRule("ZL022", "meson.version_fallback", "Meson 0.0.0 version fallback", "varies"),
    StdRule("ZL023", "meson.asciidoctor", "Meson invokes asciidoctor for man pages", "varies"),
    StdRule("ZL024", "meson.look", "Meson run_target look DESTDIR preview", "varies"),
    StdRule("ZL025", "meson.completion_install", "Meson installs bash-completion", "varies"),
    StdRule("ZL026", "rpm.missing", "Optional rpm/*.spec next to debian/", "note"),
    StdRule("ZL027", "rpm.topdir.local", "rpm/Makefile uses project-local rpmbuild", "error"),
    StdRule("ZL028", "rpm.topdir", "rpm/Makefile TOPDIR uses %_topdir", "ok"),
    StdRule("ZL029", "rpm.topdir.clean", "rpm/Makefile clean removes entire TOPDIR", "error"),
    StdRule("ZL030", "rpm.topdir.leftover", "Project-local rpmbuild/ directory", "warn"),
    StdRule("ZL031", "rpm.dynamic_version", "RPM spec Version from zfr version", "varies"),
    StdRule("ZL032", "rpm.license", "RPM spec License AGPL-3.0-or-later", "varies"),
    StdRule("ZL033", "rpm.URL", "RPM spec URL matches debian Homepage", "warn"),
    StdRule("ZL034", "rpm.Summary", "RPM spec Summary matches debian Description", "warn"),
    StdRule("ZL035", "rpm.build", "RPM spec builds with Meson not autotools", "varies"),
    StdRule("ZL036", "rpm.makefile.version", "rpm/Makefile calls zfr version", "varies"),
    StdRule("ZL037", "rpm.makefile", "rpm/Makefile convenience targets", "note"),
    StdRule("ZL038", "rpm.Requires.bash-shlib", "bash RPM spec Requires bash-shlib", "error"),
    StdRule("ZL039", "rpm.substvar", "RPM Requires without Debian substvars", "error"),
    StdRule("ZL040", "rpm.noarch.elf", "noarch RPM with Meson executable()", "error"),
    StdRule("ZL041", "rpm.debug_package.elf", "debug_package %{nil} on ELF package", "warn"),
    StdRule("ZL042", "rpm.noarch.script", "Script-only RPM needs BuildArch: noarch", "error"),
    StdRule("ZL043", "rpm.files.puff", "RPM %files lists template puff placeholder", "error"),
    StdRule("ZL044", "rpm.files.mo", "RPM %files covers gettext .mo catalogs", "varies"),
    StdRule("ZL045", "rpm.files.locale_man", "RPM %files covers locale man pages", "varies"),
    StdRule("ZL046", "rpm.files.setup", "RPM %files covers datadir/setup scripts", "varies"),
    StdRule("ZL047", "rpm.files.meson", "RPM %files covers Meson install paths", "varies"),
    StdRule("ZL048", "rpm.files.spurious_pkgdata", "RPM %files spurious package data path", "error"),
    StdRule("ZL049", "rpm.files.completion_basename", "RPM completion basename matches Meson", "error"),
    StdRule("ZL050", "i18n.l10n-level", "Configured l10n coverage level", "ok"),
    StdRule("ZL051", "i18n.po", "Optional po/ gettext directory", "note"),
    StdRule("ZL052", "i18n.linguas", "po/LINGUAS present when po/ exists", "warn"),
    StdRule("ZL053", "i18n.linguas.coverage", "LINGUAS covers required locales", "varies"),
    StdRule("ZL054", "i18n.po.files", "LINGUAS entries have matching .po files", "varies"),
    StdRule("ZL055", "i18n.man.coverage", "Whole-document man translations for level", "varies"),
    StdRule("ZL056", "i18n.man.english-copy", "Translated man still has English Name line", "warn"),
    StdRule("ZL057", "identity.*", "Directory name matches packaging identity", "varies"),
    StdRule("ZL058", "identity.meson.project", "meson project name", "ok"),
    StdRule("ZL059", "identity.source_vs_meson", "debian Source matches meson project name", "warn"),
    StdRule("ZL060", "identity.debian.Source", "debian Source field", "ok"),
    StdRule("ZL061", "identity.rpm.Name", "RPM spec Name matches package name", "varies"),
    StdRule("ZL062", "lang.shared.name", "Legacy example shared module name", "warn"),
    StdRule("ZL063", "lang.shared.example", "Template-only shared example module", "note"),
    StdRule("ZL064", "lang.bash.src", "Bash src/*.in scripts", "varies"),
    StdRule("ZL065", "lang.tests", "tests/ directory for C/C++ templates", "varies"),
    StdRule("ZL066", "lang.cobol.tests", "COBOL tests/ directory", "varies"),
    StdRule("ZL067", "lang.fortran.tests", "Fortran tests/ directory", "varies"),
    StdRule("ZL068", "lang.pascal.tests", "Pascal tests/ directory", "varies"),
    StdRule("ZL069", "lang.d.tests", "D tests/ directory", "varies"),
    StdRule("ZL070", "lang.kotlin.tests", "Kotlin tests/ directory", "varies"),
    StdRule("ZL071", "lang.nim.tests", "Nim tests/ directory", "varies"),
    StdRule("ZL072", "lang.lua.tests", "Lua tests/ directory", "varies"),
    StdRule("ZL073", "lang.python.tests", "Python tests/ directory", "varies"),
    StdRule("ZL074", "lang.zig.build", "Zig build.zig present", "error"),
    StdRule("ZL075", "lang.rust.cargo", "Rust Cargo.toml present", "error"),
    StdRule("ZL076", "lang.go.mod", "Go go.mod present", "error"),
    StdRule("ZL077", "tokens.template", "Template puff tokens expected in meta/template", "ok"),
    StdRule("ZL078", "tokens.leftover", "No leftover zephyr/some_puff1 tokens in apps", "varies"),
    StdRule("ZL079", "template.coverage", "Language template structural files present", "varies"),
    StdRule("ZL080", "readme.placeholder.*", "README still has template placeholder banner", "varies"),
    StdRule("ZL081", "readme.*", "README has no template banner", "ok"),
)

LINT_RULES = RuleRegistry(_LINT_RULES)


def lint_rule_id(code: str) -> str:
    return LINT_RULES.rule_id(code)
