= zfr(1)
Lenik <zephyr@bodz.net>
v{project-version}, {project-year}
:doctype: manpage
:manmanual: Потребителски команди
:mansource: zephyr
:man-linkstyle: blue R <>
:nofooter:

== Name

zfr - многоезични CLI проектни шаблони и помощни инструменти

== Synopsis

*zfr* *create* [*-l* _LANG_] [*-D* _DIST_] [*-1* _VER_] [*-a* _AUTHOR_]
              [*-e* _EMAIL_] _PROJECT_NAME_ [_PUFF_NAME_]...

*zfr* *rename* _PROJECT_NAME_ [_PUFF_NAME_]...

*zfr* *add* _PUFF_NAME_ [_PUFF_NAME_]...

*zfr* *remove* _PUFF_NAME_ [_PUFF_NAME_]...

*zfr* *about* [*-d*] [*-r*]

*zfr* *version* [*-g*] [*-c*] [*-r*]

*zfr* *lint* [*-l* _LEVEL_] [*-v*] [*-q*] [*--strict*] [*--color* _WHEN_]

*zfr* *shape* [*-b*] [*-v*] [*--threshold* _N_]

*zfr* *dist* [*-o* _DIR_] [*-b* _DIR_] [*-f* _FMT_] [*--rpm*]
            [*--allow-dirty*|*--no-allow-dirty*] [*--tests*]

*zfr* *ize* [*-l* _LANG_] [*-n*] [*-v*] [*--no-man*] [*--no-subst*]
           [*--color* _WHEN_]

*zfr* *release* [_OPTIONS_]

*zfr* *detect*

*zfr* *help*

*zfr-create*, *zfr-rename*, *zfr-add*, *zfr-remove*,
*zfr-about*, *zfr-version*, *zfr-lint*, *zfr-dist*, *zfr-ize*,
*zfr-shape* и *zfr-release* са тънки обвивки около същите подкоманди.

== Description

*zfr* е инструментът на командния ред за колекцията от шаблони *zephyr*.
Предоставя езикови шаблони за малки помощни програми на командния ред и
инструменти за тяхното създаване и управление.

*Важно:* очаква се инстанцираните проекти да продължат да извикват *zfr*
(например *zfr version* в *meson.build* и *rpm/Makefile*).
Низът *zfr* *не* е магически маркер за create/rename и никога
не се презаписва с името на проекта. Шаблонният запазен текст, който *се*
презаписва, остава *zephyr* (и *some_puff1* за примерни puff-ове).

Типичен работен поток:

. Създайте проект от езиков шаблон:
+
----
zfr create -l python myproj
----

. Влезте в проекта и добавете приложни *puff*-ове (примерни приложения):
+
----
cd myproj
zfr add myapp another_app
----

. По желание преименувайте проекта или премахнете puff-ове по-късно с *rename* / *remove*.

Шаблоните се намират под */usr/share/zephyr/<lang>/* при инсталация, или в дървото
с изходен код при неинсталирани builddir обвивки като *build/zfr*
(*ZFR_PKGDATADIR* го замества). Всеки шаблон може да включва примерен puff с име
*some_puff1*; подайте имена на puff-ове на командния ред на *create*, за да ги
инстанцирате, или ги пропуснете за празен проект.

В monorepo *repodir* е коренът на git (или meta) checkout, а *packagedir*
е дървото на пакета със zephyr форма (например *repodir/bash*).
Командите, които обхождат от текущата директория, първо определят *packagedir*.

*i18n*::
  *zfr lint -l/--l10n-level* избира изискваното покритие с gettext и ръководства.
  *L0* не изисква нищо. *L1* (по подразбиране) изисква *de*, *es*, *fr*, *it*, *ja*,
  *ko*, *pl*, *ru*, *zh_CN*, *zh_TW*. *L2* изисква тези плюс *bg*, *ca*,
  *cs*, *el*, *hu*, *id*, *nl*, *pt*, *sv*, *tr*. *L3* добавя *da*, *et*, *fi*,
  *gl*, *hr*, *lt*, *ms*, *pt_BR*, *uk*, *vi*. Английският (*en*) е изходният
  *msgid* език и не се изброява в *po/LINGUAS*. Допълнителни локали над
  нивото са позволени. Поставете аргументите по подразбиране за *lint* в
  *.config/zfr/lint.options*. Ръководствата трябва да са цялостни
  ръчни преводи под *docs/<locale>/* (не po4a фрагменти).

== Commands

*create*::
  Копира *pkgdatadir/<lang>/* в нова директория *./<project_name>/* (грешка, ако
  директорията вече съществува). Презаписва *zephyr* → *_PROJECT_NAME_* и, когато
  са дадени имена на puff-ове, *some_puff1* → първото *_PUFF_NAME_* (допълнителни
  чрез *add*). Без имена на puff-ове премахва шаблонните puff файлове, но запазва
  маркерите *some_puff1*, за да може по-късно *add* да ги инстанцира.
  Записва нов *debian/changelog* (шаблонният changelog се отхвърля) с
  *--distribution* / *--init-version* / *--author* / *--email*, след което изпълнява
  *git init*, задава *core.hooksPath* на *.githooks* (копира *pre-commit*, за да
  синхронизира *VERSION* с *debian/changelog*), начален commit и анотиран tag *vVER*.

*rename*::
  В текущата проектна директория презаписва *zephyr* → *_PROJECT_NAME_* и,
  за всяко дадено име, шаблонния puff *some_puff1* → това име.
  Не презаписва *zfr*.

*add*::
  Открива езика на проекта и копира шаблонните puff файлове в текущия
  проект, преименувайки *some_puff1* на всяко *_PUFF_NAME_*. Актуализира Meson
  списъците (или еквивалентното свързване), когато е възможно.

*remove*::
  Премахва файлове и Meson свързване за всяко дадено име на puff от текущия
  проект.

*detect*::
  Отпечатва открития език за текущата директория
  (обхожда родителски директории до корена на проекта).

*about*::
  Отпечатва информация за текущия проект. Обхожда от текущата
  директория към родителите, за да намери корена на проекта (*meson.build* с
  *project()* или *debian/control*). Общите полета (име, версия, лиценз,
  начална страница, поддържащ, резюме, section, priority, distribution,
  architecture) се анализират от Debian или RPM метаданни и се пренасят според
  ширината на терминала. Също отпечатва брой файлове/редове изходен код и
  оценен размер на payload. Интерактивните терминали използват CSR (console SGR)
  цветове, освен ако *NO_COLOR* е зададено. Използвайте *-d* / *-r* за пълен
  анализиран Debian или RPM изглед (не dump на опаковъчните файлове).

*version*::
  Отпечатва текущата версия на проекта (един ред, за скриптове). По подразбиране е
  *git describe*, когато *git* и *.git* са налични, иначе последната версия от
  *debian/changelog*. Резервно *VERSION* файл, след това *0.0.0*.
  Несемver маркер (например git hash) се обвива като *0.0.0-<token>*.

*lint*::
  Валидира текущия проект спрямо zephyr стила на опаковане и оформление
  (обхожда от текущата директория към родителите до корена на проекта).
  Докладва липсващи файлове, несъответствия в идентичността, Meson/Debian/RPM
  грешки, останали *zephyr* / *some_puff1* маркери в инстанцирани приложения и
  предложени поправки. Споменаванията на *zfr* са очаквани и не се третират като
  остатъци. За *.githooks/pre-commit* обхожда до *.git*, спазва *core.hooksPath*
  и проверява дали hook-ът синхронизира *VERSION* от *debian/changelog*.
  Когато *po/* или *docs/\*.adoc* присъстват, предупреждава, ако покритието не
  отговаря на *--l10n-level* (виж *i18n* под Description; по подразбиране *L1*,
  проектният файл *.config/zfr/lint.options* може да зададе друго ниво).
  Изходът е предназначен за хора и AI програмисти: всяко откритие има код,
  път и конкретна поправка. Интерактивните терминали използват CSR (console SGR)
  цветове, освен ако *NO_COLOR* е зададено.

*shape*::
  Отпечатва *zephyr shape* резултат 0–100 за текущия *packagedir* (колко
  пълно дървото съответства на zephyr стила на опаковане). В monorepo
  *packagedir* може да се различава от *repodir* (git / meta корен); инструментите
  използват shape, за да предпочитат директорията на пакета пред корена на хранилището.
  *\-b* / *--bool* отпечатва *1*, ако резултатът е поне прага
  (по подразбиране *50*), иначе *0*.

*dist*::
  Създава архив с изходен код на текущия проект (обхожда от текущата
  директория към родителите до корена на проекта). Когато тази директория
  е git коренът на проекта, изпълнява *meson dist* (след *meson setup*, по
  подразбиране *--allow-dirty* и *--no-tests*). Вложените езикови шаблони нямат
  собствен *.git*, затова *meson dist* би опаковал родителското meta-repo;
  тези дървета получават tarball само на този проект. Отпечатва пътя на архива
  на stdout. *rpm/Makefile* *dist* и Meson *srcdist* ninja целта преизползват
  тази команда.

*release*::
  Анализира същите опции като *gh-makerelease*(1), пресъздава argv и *exec*
  *gh-makerelease* от PATH. Тази команда сама не реализира тагване,
  опаковане или GitHub качвания. Проектът *zephyr* се пуска от git checkout
  корена (езикови шаблони плюс *zfr/*). Виж *Options for release* по-долу.

*ize*::
  Рефакторира текущия проект на място, за да съответства на текущия zephyr
  стил (обхожда от текущата директория към родителите). Копира липсващата
  *debian/* и *rpm/* структура от езиковия шаблон (имената презаписани за
  този проект), записва *VERSION* и *.githooks/pre-commit*,
  поправя *meson.build* (*zfr version*, *asciidoctor* man цели,
  *run_target look*, bash-completion инсталация). Преобразува groff *\*.1* man
  страници под проекта (не *debian/*) в *docs/\*.adoc* с Meson правила,
  и hardcoded changelog версии в *src/* в *\*.in*
  *@VERSION@* замествания или *PROJECT_VERSION* чрез *config.h* за C
  семейство езици. *\-n* / *--dry-run* отпечатва плана без запис.
  След това изпълнете *zfr lint*.

*help*::
  Показва помощ за командния ред.

== Options

Опции за *create*:

*-l, --lang* _LANG_::
  Езиков шаблон за използване (по подразбиране: *python*).
  Поддържани стойности включват *bash*, *c*, *clib*, *cpp*, *cpplib*, *csharp*, *erlang*, *go*,
  *haskell*, *java*, *perl*, *python*, *ruby*, *rust*, *smalltalk*, *swift* и
  *typescript*.

*-D, --distribution* _DIST_::
  Debian changelog distribution (по подразбиране: *unstable*).

*-1, --init-version* _VER_::
  Начална версия на пакета и git tag (по подразбиране: *0.0.1*).

*-a, --author* _AUTHOR_::
  Име на автор в changelog и git (по подразбиране: *Lenik (谢继雷)*).

*-e, --email* _EMAIL_::
  Имейл на автор в changelog и git (по подразбиране: *lenik@bodz.net*).

Опции за *about*:

*-d, --debian*::
  Показва анализирани Debian опаковъчни полета (*debian/control*, последната
  секция в *debian/changelog*). Списъци като *Build-Depends* се пренасят според
  ширината на терминала; дългото описание се пренарежда на параграфи.

*-r, --redhat*::
  Показва анализирани RPM опаковъчни полета от *rpm/*.spec* (макроси като
  *%{version}* се показват с *zfr version -r*). Тялото на *%description*
  се пренарежда; spec scriptlet-ите не се dump-ват.

*--color* _WHEN_::
  CSR подчертаване: *auto* (по подразбиране: TTY и без *NO_COLOR*), *always* или
  *never*.

Опции за *version*:

*-g, --git*::
  Използва *git describe --tags --always --dirty* (по подразбиране, когато *git* и *.git*
  са налични).

*-c, --changelog*::
  Използва последната версия от *debian/changelog* (по подразбиране, когато *git* или *.git* липсват).

*-r, --rpm*::
  Отпечатва RPM-съвместима *Version* (тире се заменят с долни черти).

Опции за *lint*:

*-v, --verbose*::
  Отпечатва и успешните проверки.

*-q, --quiet*::
  Отпечатва само грешки.

*--strict*::
  Третира предупрежденията като грешки (exit status 1).

*-l, --l10n-level* _LEVEL_::
  Изисквано gettext и цялостно manpage покритие: *L0* (няма), *L1*
  (10 локала, по подразбиране), *L2* (20) или *L3* (30). *LEVEL* може да е *L2* или
  *2*. Стойностите по подразбиране идват и от *.config/zfr/lint.options*.

*--color* _WHEN_::
  CSR подчертаване: *auto* (по подразбиране: TTY и без *NO_COLOR*), *always* или
  *never*.

Опции за *shape*:

*-b, --bool*::
  Отпечатва *1*, ако shape резултатът е поне *--threshold*, иначе *0*.

*-v, --verbose*::
  Отпечатва *packagedir*, *repodir*, *role* и *threshold* на standard error.

*--threshold* _N_::
  Праг за *--bool* (по подразбиране: *50*).

Опции за *dist*:

*-o, --output* _DIR_::
  Записва архива в *_DIR_* (по подразбиране: Meson *meson-dist*
  директория, или *%_topdir/SOURCES* ($HOME/rpmbuild) с *--rpm*).

*-b, --builddir* _DIR_::
  Meson build директория. По подразбиране */build*, когато този builddir е
  конфигуриран за това изходно дърво, иначе *<project>/build*.

*-f, --format* _FMT_::
  Формат на архива: *xz* (по подразбиране), *gz* или *zip*.

*--rpm*::
  Именува архива *_NAME_*-*_VERSION_*.tar.xz и го записва в
  *%_topdir/SOURCES* ($HOME/rpmbuild), освен ако е зададено *-o*. Използва се от *rpm/Makefile*.

*--allow-dirty*, *--no-allow-dirty*::
  Подава *--allow-dirty* на *meson dist* (по подразбиране: позволено).

*--tests*::
  Изпълнява тестове по време на *meson dist* (по подразбиране е *--no-tests*).

Опции за *release* (анализирани тук, предавани на *gh-makerelease*):

*-b, --build-binary*::
  Debian само бинарен build (*-b*); без _.dsc_.
*-n, --no-pre-clean*::
  Преизползва Debian build кеша.
*-u, --upload*::
  Преизползва съществуващи артефакти за версията, ако има такива.
*--unsigned*::
  Създава неподписани Debian пакети (*-us -uc*).
*-p, --dput-host* _HOST_::
  *dput*(1) host за качване на _.changes_ файла.
*-d, --docker*::
  Създава Debian пакет с *build4*(1) в Docker.
*-B, --base-image* _IMAGE_::
  Целеви image за *build4* (по подразбиране: *b4f-debian:trixie*).
*-s, --docker-server* _SERVER_::
  Изпълнява *build4* през SSH на *SERVER* (подразбира *-d*).
*-l, --local*::
  Само build; без таг, push или GitHub release.
*-f, --force*::
  Заменя съществуващ tag/release.
*-I, --no-install*::
  Пропуска *sudo dpkg -i*.
*-T, --no-tag*::
  Пропуска създаването и push на git release tag.
*-U, --no-upload*::
  Пропуска *dput* на _.changes_ файла.
*-R, --no-release*::
  Пропуска създаването на GitHub release.
*-P, --no-publish*::
  Пропуска публикуване в VSIX marketplace.
*-Y, --no-rpm*::
  Пропуска *make -C rpm rpm srpm*.
*-D, --no-deb*::
  Пропуска Debian *debuild*.
*-v, --verbose*::
  Подробно логване (повтаряемо).
*-q, --quiet*::
  По-малко изход (повтаряемо).

Опции за *ize*:

*-l, --lang* _LANG_::
  Езиков шаблон, от който да се копира структурата (по подразбиране: откриване).

*-n, --dry-run*::
  Отпечатва планираните добавки/актуализации/преобразувания без запис на файлове.

*-v, --verbose*::
  Отпечатва и пропуснатите пътища, които вече съществуват.

*--no-man*::
  Не преобразува groff *\*.1* източници в *docs/\*.adoc*.

*--no-subst*::
  Не презаписва hardcoded версии в *src/* към *@VERSION@* / *config.h*.

*--color* _WHEN_::
  CSR подчертаване: *auto* (по подразбиране: TTY и без *NO_COLOR*), *always* или
  *never*.

== Environment

*ZFR_PKGDATADIR*::
  Замества корена на шаблоните (обикновено */usr/share/zephyr*).

*NO_COLOR*::
  Когато е зададено, *zfr about*, *zfr lint* и *zfr ize* изключват CSR
  подчертаване в режим *--color auto*.

*PYTHONPATH*::
  Трябва да включва директорията, съдържаща пакета *zfr_lib*, когато
  инструментите се изпълняват от нестандартна инсталационна структура.

== Tests

Изходното дърво (не инсталираният пакет) включва *tests/* с
Python *unittest* покритие на CLI. *meson test* (build директория
*/build*) открива *tests/test_*.py*. Тестовете създават временни примерни
проекти и упражняват всяка подкоманда (*create*, *add*, *remove*,
*rename*, *about*, *version*, *lint*, *shape*, *dist*, *ize*, *release*,
*detect*, *help*), обвивките *zfr-**, оценка на езикова увереност,
gettext каталози и ръководствата *docs/<lang>/zfr.adoc* за всеки locale.
Без Meson задайте *ZFR_PKGDATADIR* на zephyr checkout корена (родител на *zfr/*)
и *PYTHONPATH* на *src/*.

== Files

*.config/zfr/lint.options*::
  Аргументи по подразбиране за *zfr lint* за този проект (shell токени; *#* коментари).
  Самият zfr CLI доставя *-l 2*.

*/usr/share/zephyr/<lang>/*::
  Инсталирани езикови шаблони.

*/usr/bin/zfr*, */usr/bin/zfr-\**::
  CLI и тънки обвивки.

*/usr/share/doc/zephyr/*::
  Документация на пакета (LICENSE, README).

*/usr/share/man/<locale>/man1/zfr.1*::
  Локализирани man страници, изградени от *docs/<locale>/zfr.adoc*
  (цялостни преводи на документи, не gettext/po4a фрагменти).
  Българският източник на ръководството е *docs/bg/zfr.adoc*.

== Exit status

*0*::
  Успех. За *lint* проектът няма открития на ниво грешка
  (предупрежденията все пак се отпечатват, освен ако не е *--strict*).

*non-zero*::
  Възникна грешка (неизвестен език, дестинацията съществува, неуспешно откриване,
  липсващи puff файлове, *lint* открития и т.н.).

== Author

Автор: {project-author} <{project-email}>.

== Copyright

Copyright (C) {project-year}.
Лиценз AGPL-3.0-or-later.
Това е свободен софтуер: можете да го променяте и разпространявате при
условията на GNU Affero General Public License.
НЯМА ГАРАНЦИЯ, доколкото законът позволява.
Вижте файла LICENSE в изходното разпространение за пълния текст на лиценза,
включително допълнителни условия, че този проект се противопоставя на AI експлоатация и
AI хегемония, и отхвърля безмислено MIT-стил лицензиране и политически наивно
BSD-стил лицензиране.
